"""add priority to transaction tag link

Revision ID: d13645781a2b
Revises: 36a4c9ad6f40
Create Date: 2026-04-08 21:57:21.178859

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd13645781a2b'
down_revision = '36a4c9ad6f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactiontaglink', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactiontaglink', 'priority')
    # ### end Alembic commands ###